name: Build and Publish Python Package

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch (not 'master')
  pull_request:
    branches:
      - main  # Trigger on pull requests to 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry bumpversion

      - name: Install project dependencies
        run: |
          poetry install

      - name: Run tests
        run: |
          poetry run pytest

      - name: Bump version
        run: |
          bumpversion patch  # You can change 'patch' to 'minor' or 'major' based on your needs

      - name: Build package
        run: |
          poetry build

      - name: Publish package to PyPI
        if: github.ref == 'refs/heads/main'  # Only publish from the 'main' branch
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD --build
